### ISSUE TITLE
It no longer works

### ISSUE THREAD

**Issue by MiClobiMC** [peter-marshall5/gartic-phone-auto-draw#1]
A few days ago it stopped working it only appears when they are rooms created by me but if they are rooms created by other users it does not work it does not appear to add the photo

**Comment by peter-marshall5** [comment]
From my testing everything is still working as intended as of now. Could it be an issue with your user script manager, or your network connection? Would you mind sending a screenshot of the issue with the developer console open? (Right click, Inspect, Console)

**Comment by MiClobiMC** [comment]
![WZnRyrf](https://user-images.githubusercontent.com/60762569/194955377-cf9bba18-abb9-4026-b665-7a2682d91575.png)
I already saw the console nothing appears

**Comment by peter-marshall5** [comment]
From the screenshots it looks like the auto draw script is either not getting injected into the page properly or not finding the right place to add the plus button. So far I am not able to reproduce the issue on my end but I'm still looking into it.

For now, try reloading the page twice before joining the game.

**Comment by MiClobiMC** [comment]
It's working again
