### ISSUE TITLE
It didn't work for me

### ISSUE THREAD

**Issue by alvaromaltrain** [peter-marshall5/gartic-phone-auto-draw#3]
When the album of the drawings is shown, it appears blank

**Comment by peter-marshall5** [comment]
Hmm... It seems like they also changed the data format for tool path packets. Currently working on a fix...

**Comment by peter-marshall5** [comment]
Unfortunately the servers now seem to be rate-limited. That means it's unlikely to be possible to get the draw bot working again since it relies on sending lots of packets quickly.

**Comment by alvaromaltrain** [comment]
Thank you very much, if it works, it doesn't matter if it's low quality, the important thing is that it works, I think you should do something like this in your extension to send fewer packets.
