### ISSUE TITLE
The picture does not display in the album

### ISSUE THREAD

**Issue by ILoveCurlyHairChoi** [peter-marshall5/gartic-phone-auto-draw#4]
Hello,

I was just wondering why it does not display in the album
![aaaaaa](https://user-images.githubusercontent.com/130273584/230764759-55656be3-d1a7-43bb-99b9-64aa796f64c3.PNG)
![lkmklml](https://user-images.githubusercontent.com/130273584/230764769-a2cdf77e-f834-41bc-b8df-973f03015834.PNG)
![kmkml](https://user-images.githubusercontent.com/130273584/230764773-5d89f245-0673-45dc-85d9-50d3fb4190ba.PNG)

thanks

**Comment by peter-marshall5** [comment]
Auto drawing was patched by the Gartic Phone team somewhere around January or Feburary, as indicated on the front page of this repo.  See [this script](https://greasyfork.org/en/scripts/436728-gartic-phone-draw-bot) instead (Not made by me) for something that still works after the patch.
